// Package backtest replays strategy logic over stored history.
//
// It reports cumulative return, realized APR, max drawdown, funding reversal
// count, and the share of periods that were profitable.
//
// Two correctness rules that separate a useful backtest from a misleading one:
//
//   - Funding is a DISCRETE event. A position earns nothing unless it is open
//     at the settlement timestamp. Count settlements crossed; never multiply an
//     APR by a holding duration.
//   - Filter out irregular rates (Binance rateType "Special", generated by
//     dividends) or they contaminate the baseline.
//
// Introduced in: PLAN.md phase 3, step 3.3.
package backtest
